[tools]
dotnet = "10.0.301"

[tasks.watch]
description = "Watch and run test project"
run = "dotnet watch run --project ObsStrawket.Test/ObsStrawket.Test.csproj"

[tasks.lint]
description = "Report C# code-style and analyzer diagnostics"
run = "mise run --continue-on-error lint:style ::: lint:analyzers"

[tasks.fix]
description = "Try fixing C# code-style and analyzer diagnostics"
run = [
 "dotnet format analyzers --severity hidden",
 "dotnet format style --severity hidden"
]

[tasks.update-protocol]
description = "Update Obs.h and protocol.json for new API reflection"
run = "dotnet run --project SourceGenerator/SourceGenerator.csproj -- --update-upstream"

[tasks.generate-protocol]
description = "Regenerate client API from the tracked upstream revision"
run = "dotnet run --project SourceGenerator/SourceGenerator.csproj"

[tasks."lint:style"]
hide = true
run = "dotnet format style --verify-no-changes --severity hidden"

[tasks."lint:analyzers"]
hide = true
run = "dotnet format analyzers --verify-no-changes --severity hidden"
