name: publish

on:
  push:
    branches: [release]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Setup
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: "6.0"
      - name: Test
        run: dotnet test
      - name: Package
        run: dotnet pack --include-source --include-symbols --configuration Release
      - name: Publish
        run: dotnet nuget push ObsStrawket/bin/Release/*.nupkg  --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      - name: Setup nbgv
        uses: dotnet/nbgv@master
        with:
          setAllVars: true
      - name: Create tag
        run: nbgv tag && git push origin $NBGV_NuGetPackageVersion
