name: nuget publish

on:
  push:
    branches: [release]

jobs:
  publish:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      # Setup .NET SDK
      - name: Setup
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: "6.0"
      # Run dotnet build and package
      - name: Package
        run: dotnet pack --configuration Release
      # Publish the package to GitHub Package Registry
      - name: Publish
        run: dotnet nuget push ObsStrawket\bin\Release\*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
