name: Test & Publish

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Setup
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: "7.0"
      - name: Test
        run: dotnet test
      - id: versioning
        name: Set version
        run: echo "::set-output name=version::$(nbgv get-version -v SimpleVersion)$(nbgv get-version -v PrereleaseVersion)"
      - name: Publish & Create tag
        run: "[ $(git tag -l v${{ steps.versioning.outputs.version }}) ] || (dotnet pack --include-source --configuration Release -p:Version=${{ steps.versioning.outputs.version }} && dotnet nuget push ObsStrawket/bin/Release/*.symbols.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json && nbgv tag && git push origin v${{ steps.versioning.outputs.version }})"
