name: Test & Publish

on:
  push:
    branches: [main, dev]

jobs:
  test:
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_NOLOGO: true
    outputs:
      version: ${{ steps.versioning.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Setup
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: "7.0"
      - name: Test
        run: dotnet test
      - id: versioning
        name: Set publish
        if: matrix.os == 'ubuntu-latest'
        run: |
          version="$(nbgv get-version -v SimpleVersion)$(nbgv get-version -v PrereleaseVersion)"
          [ $(git tag -l v$version) ] || (echo version=$version >> "$GITHUB_OUTPUT")

  publish:
    needs: test
    if: needs.test.outputs.version && github.ref_name == 'main'
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Setup
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: "7.0"
      - name: Publish
        run: |
          version=${{needs.test.outputs.version}}
          dotnet pack --include-source --configuration Release -p:Version=$version
          dotnet nuget push ObsStrawket/bin/Release/*.symbols.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json
          git tag v$version
          git push origin v$version
